version: "3"
volumes:
  md_data:
  traefik_certs:
networks:
  default:
    name: mongodb_network
services:
  traefik:
    image: traefik:v2.6
    container_name: "traefik"
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - md_data:/data/db
    ports:
      - "27017:27017"
  ana:
    build:
      context: .
      target: "ana"
    container_name: "ana"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.ana_rt.entrypoints=websecure
      - traefik.http.routers.ana_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/ana`)
      - traefik.http.routers.ana_rt.tls=true
      - traefik.http.routers.ana_rt.tls.certresolver=production
    expose:
      - "3000"
  api:
    build:
      context: .
      target: "api"
    container_name: "api"
    restart: always
    networks:
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_rt.entrypoints=websecure
      - traefik.http.routers.api_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/`)
      - traefik.http.routers.api_rt.tls=true
      - traefik.http.routers.api_rt.tls.certresolver=production
    expose:
      - "3000"
  cron:
    build:
      context: .
      target: "cron"
    container_name: "cron"
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.cron_rt.entrypoints=websecure
      - traefik.http.routers.cron_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/cron`)
      - traefik.http.routers.cron_rt.tls=true
      - traefik.http.routers.cron_rt.tls.certresolver=production
    expose:
      - "3000"
  integrated:
    build:
      context: .
      target: "integrated"
    container_name: "integrated"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.integrated_rt.entrypoints=websecure
      - traefik.http.routers.integrated_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/integrated`)
      - traefik.http.routers.integrated_rt.tls=true
      - traefik.http.routers.integrated_rt.tls.certresolver=production
    expose:
      - "3000"
  stations:
    build:
      context: .
      target: "stations"
    container_name: "stations"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.stations_rt.entrypoints=websecure
      - traefik.http.routers.stations_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/stations`)
      - traefik.http.routers.stations_rt.tls=true
      - traefik.http.routers.stations_rt.tls.certresolver=production
    expose:
      - "3000"
  users:
    build:
      context: .
      target: "users"
    container_name: "users"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.users_rt.entrypoints=websecure
      - traefik.http.routers.users_rt.rule=Host(`api.smartwolke.eletrify.io`) && PathPrefix(`/users`)
      - traefik.http.routers.users_rt.tls=true
      - traefik.http.routers.users_rt.tls.certresolver=production
    expose:
      - "3000"
